### ISSUE TITLE
The meaning of "Has Online" is not intuitive

### ISSUE THREAD

**Issue by christhomson** [darinyu/WatCourse#1]
Hey there, cool site!

One odd thing I noticed was when searching for a course is that some courses are listed as having an online offering ("Has Online"), but that doesn't necessarily mean those courses have an online offering for _this_ term (Winter 2015 currently) - it just [means they are offered online sometimes](https://github.com/uWaterloo/api-documentation/blob/master/v2/courses/subject_catalog_number.md#response). Maybe change the way that is communicated in the UI, or update the data to only show "Has Online" for courses that actually have online offerings in Winter 2015?

PSYCH 261 is an example of this.

**Comment by darinyu** [comment]
Thanks for your suggestion. I actually haven't noticed this until you mentioned. I will check if there is a way to check if the specific course is offered online for the specific term. And as you said, it definitely needs a UI string update. Thanks again.
